using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using Unity.EditorCoroutines.Editor;
using UnityEditor;
using UnityEngine;

namespace UniRmmz.Editor
{
    
    public class GenerateScriptCommand
    {
        [MenuItem("UniRmmz/Tools/GenerateScriptCommand")]
        public static void Generate()
        {
            if (Application.isPlaying)
            {
                EditorApplication.isPlaying = false;
            }

            EditorCoroutineUtility.StartCoroutineOwnerless(GenerateCoroutine());
        }
        
        private static IEnumerator GenerateCoroutine()
        {
            Rmmz.DataManager.LoadDatabase();
            yield return new WaitUntil(() => Rmmz.DataManager.IsDatabaseLoaded());

            var outputPath = Path.GetFullPath(Path.Combine(Application.streamingAssetsPath,
                "..\\Scripts\\UniRmmz\\Generated\\RmmzScriptCommand.Generated.cs"));
            var allCodes = new List<RmmzJavascriptCode>();
            
            CollectFromCommonEvent(allCodes);

            foreach (var data in Rmmz.dataMapInfos)
            {
                if (data == null)
                {
                    continue;
                }
                
                Rmmz.DataManager.LoadMapData(data.Id);
                yield return new WaitUntil(() => Rmmz.DataManager.IsMapLoaded());

                CollectFromMapEvent(allCodes);
            }
            
            GenerateAndSave(allCodes.Distinct(), outputPath);
        }

        private static void CollectFromMapEvent(List<RmmzJavascriptCode> allCodes)
        {
            for (int i = 0; i < Rmmz.DataMap.Events.Count; i++)
            {
                var ev = Rmmz.DataMap.Events[i];
                if (ev != null && ev.Id != 0)
                {
                    foreach (var page in ev.Pages)
                    {
                        for (int j = 0; j < page.List.Count; ++j)
                        {
                            if (page.List[j].Code == 355)
                            {
                                var code = new RmmzJavascriptCode();
                                code.AddLine(Convert.ToString(page.List[j].Parameters[0]));
                                while (i + 1 < page.List.Count && page.List[j + 1].Code == 655)
                                {
                                    code.AddLine(Convert.ToString(page.List[j + 1].Parameters[0]));
                                    j++;
                                }
                                allCodes.Add(code);
                            }
                        }
                            
                    }
                }
            }
        }

        private static void CollectFromCommonEvent(List<RmmzJavascriptCode> allCodes)
        {
            foreach (var data in Rmmz.dataCommonEvents)
            {
                if (data == null)
                {
                    continue;
                }

                for (int i = 0; i < data.List.Count; ++i)
                {
                    if (data.List[i].Code == 355)
                    {
                        var code = new RmmzJavascriptCode();
                        code.AddLine(Convert.ToString(data.List[i].Parameters[0]));
                        while (i + 1 < data.List.Count && data.List[i + 1].Code == 655)
                        {
                            code.AddLine(Convert.ToString(data.List[i + 1].Parameters[0]));
                            i++;
                        }
                        allCodes.Add(code);
                    }
                }
            }
        }

        private static void GenerateAndSave(IEnumerable<RmmzJavascriptCode> allCodes, string outputPath)
        { 
            var generatedCode = GenerateRmmzScriptCode(allCodes);
        
            try
            {
                File.WriteAllText(outputPath, generatedCode);
                AssetDatabase.Refresh();
            
                EditorUtility.DisplayDialog("Success", 
                    $"Code generated successfully!\nSaved to: {outputPath}", "OK");
            }
            catch (System.Exception e)
            {
                EditorUtility.DisplayDialog("Error", $"Failed to save file: {e.Message}", "OK");
            }
        }


        private static string GenerateRmmzScriptCode(IEnumerable<RmmzJavascriptCode> allCodes)
        {
            var sb = new StringBuilder();
            
            // ファイルヘッダー
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine();
        
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine();
        
            // 名前空間とクラス
            sb.AppendLine($"namespace UniRmmz");
            sb.AppendLine("{");
            sb.AppendLine($"    public static partial class RmmzScriptCommand");
            sb.AppendLine("    {");
        
            // 静的コンストラクタ
            sb.AppendLine("        static RmmzScriptCommand()");
            sb.AppendLine("        {");
            sb.AppendLine("            Clear();");
        
            foreach (var code in allCodes)
            {
                if (code.IsEmpty())
                {
                    continue;
                }
            
                var csharpCode = code.Lines.Select(line => ConvertCodeToCSharp(line));

                sb.AppendLine($"           Add(@\"{code.GenerateCode()}\"");
                sb.AppendLine("                , (self) => ");
                sb.AppendLine("            {");
                foreach (var line in csharpCode)
                {
                    sb.AppendLine($"\t\t\t\t{line}");
                }
                sb.AppendLine("            });");
                sb.AppendLine();
            }
        
            sb.AppendLine("        }");
            sb.AppendLine();
        
            sb.AppendLine("    }");
            sb.AppendLine("}");
        
            return sb.ToString();
        }
        
        private static string ConvertCodeToCSharp(string code)
        {
            var csharpCode = code;
        
            csharpCode = AutoCapitalizeProperties(csharpCode);
        
            var replacements = new Dictionary<string, string>
            {
                { @"Math\.", "Mathf." },
                { @"===", "==" },
                { @"!==", "!=" },
                { @"\'", "\"" },
                { @"\b(let|const)\s+", "var " },
                { @"\bthis\b", "self" },
                { @"\$data([A-Z]\w*)", "Rmmz.data$1" },
                { @"\$game([A-Z]\w*)", "Rmmz.game$1" },
            };
        
            foreach (var replacement in replacements)
            {
                csharpCode = Regex.Replace(csharpCode, replacement.Key, replacement.Value);
            }
        
            return $"{csharpCode}";
        }
    
        /// <summary>
        /// プロパティ/メソッド名と思われる単語を先頭大文字にする
        /// </summary>
        private static string AutoCapitalizeProperties(string formula)
        {
            // .プロパティ のパターンを検出して先頭大文字化
            var propertyPattern = @"\.\s*([a-z][a-zA-Z0-9_]*)\b";
        
            formula = Regex.Replace(formula, propertyPattern, match =>
            {
                var propertyName = match.Groups[1].Value;
            
                // 先頭を大文字に変換
                var capitalizedProperty = char.ToUpper(propertyName[0]) + propertyName.Substring(1);
            
                return $".{capitalizedProperty}";
            });

            // メソッド呼び出しのパターン object.method( を検出
            var methodPattern = @"\b([a-zA-Z_]\w*)\s*\.\s*([a-z][a-zA-Z0-9_]*)\s*\(";
        
            formula = Regex.Replace(formula, methodPattern, match =>
            {
                var objectName = match.Groups[1].Value;
                var methodName = match.Groups[2].Value;
            
                // 先頭を大文字に変換
                var capitalizedMethod = char.ToUpper(methodName[0]) + methodName.Substring(1);
            
                return $"{objectName}.{capitalizedMethod}(";
            });

            return formula;
        }
    
        private static string EscapeString(string input)
        {
            return input?.Replace("\"", "\"\"") ?? "";
        }
    }
}